import Head from 'next/head';
import Image from 'next/image';

const Login = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
            </Head>
            <section>
                <div>
                    <h1>Home</h1>
                </div>
            </section>
        </>
    );
};

export default Login;
